/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonaPersonaIdRouteImport } from './routes/persona.$personaId'
import { Route as ApiEvaluateRouteImport } from './routes/api/evaluate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as PersonaPersonaIdIndexRouteImport } from './routes/persona.$personaId.index'
import { Route as PersonaPersonaIdThreadIdRouteImport } from './routes/persona.$personaId.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaPersonaIdRoute = PersonaPersonaIdRouteImport.update({
  id: '/persona/$personaId',
  path: '/persona/$personaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateRoute = ApiEvaluateRouteImport.update({
  id: '/api/evaluate',
  path: '/api/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaPersonaIdIndexRoute = PersonaPersonaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonaPersonaIdRoute,
} as any)
const PersonaPersonaIdThreadIdRoute =
  PersonaPersonaIdThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => PersonaPersonaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/persona/$personaId': typeof PersonaPersonaIdRouteWithChildren
  '/persona/$personaId/$threadId': typeof PersonaPersonaIdThreadIdRoute
  '/persona/$personaId/': typeof PersonaPersonaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/persona/$personaId/$threadId': typeof PersonaPersonaIdThreadIdRoute
  '/persona/$personaId': typeof PersonaPersonaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/persona/$personaId': typeof PersonaPersonaIdRouteWithChildren
  '/persona/$personaId/$threadId': typeof PersonaPersonaIdThreadIdRoute
  '/persona/$personaId/': typeof PersonaPersonaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/evaluate'
    | '/persona/$personaId'
    | '/persona/$personaId/$threadId'
    | '/persona/$personaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/evaluate'
    | '/persona/$personaId/$threadId'
    | '/persona/$personaId'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/evaluate'
    | '/persona/$personaId'
    | '/persona/$personaId/$threadId'
    | '/persona/$personaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEvaluateRoute: typeof ApiEvaluateRoute
  PersonaPersonaIdRoute: typeof PersonaPersonaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$personaId': {
      id: '/persona/$personaId'
      path: '/persona/$personaId'
      fullPath: '/persona/$personaId'
      preLoaderRoute: typeof PersonaPersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate': {
      id: '/api/evaluate'
      path: '/api/evaluate'
      fullPath: '/api/evaluate'
      preLoaderRoute: typeof ApiEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$personaId/': {
      id: '/persona/$personaId/'
      path: '/'
      fullPath: '/persona/$personaId/'
      preLoaderRoute: typeof PersonaPersonaIdIndexRouteImport
      parentRoute: typeof PersonaPersonaIdRoute
    }
    '/persona/$personaId/$threadId': {
      id: '/persona/$personaId/$threadId'
      path: '/$threadId'
      fullPath: '/persona/$personaId/$threadId'
      preLoaderRoute: typeof PersonaPersonaIdThreadIdRouteImport
      parentRoute: typeof PersonaPersonaIdRoute
    }
  }
}

interface PersonaPersonaIdRouteChildren {
  PersonaPersonaIdThreadIdRoute: typeof PersonaPersonaIdThreadIdRoute
  PersonaPersonaIdIndexRoute: typeof PersonaPersonaIdIndexRoute
}

const PersonaPersonaIdRouteChildren: PersonaPersonaIdRouteChildren = {
  PersonaPersonaIdThreadIdRoute: PersonaPersonaIdThreadIdRoute,
  PersonaPersonaIdIndexRoute: PersonaPersonaIdIndexRoute,
}

const PersonaPersonaIdRouteWithChildren =
  PersonaPersonaIdRoute._addFileChildren(PersonaPersonaIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEvaluateRoute: ApiEvaluateRoute,
  PersonaPersonaIdRoute: PersonaPersonaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
